import { SimulationEngine } from '../simulation/SimulationEngine.mjs';
import { generateMaterial, mulberry32 } from '../materials/MaterialGenerator.mjs';
import { sanitizeMaterial } from '../materials/MaterialDefinition.mjs';
import { PRESETS } from '../materials/Presets.mjs';
import { GravityController } from '../sensors/GravityInputProvider.mjs';
import { AdaptiveQuality } from '../performance/AdaptiveQuality.mjs';
import { saveSetup, loadSavedSetup, exportSetup, importSetupFile } from './storage.mjs';
import { PhaseName } from '../simulation/Phase.mjs';
import { SceneRenderer } from '../rendering/SceneRenderer.mjs';
import { pointerDistance, pointerMidpoint, pinchCameraDistance } from './gestureMath.mjs';

const $=(id)=>document.getElementById(id);
const sim=new SimulationEngine(1800); const gravity=new GravityController(); const quality=new AdaptiveQuality();
let seed=1337,nextMaterialId=1,selectedMaterialId=0,mode='brush',renderer,last=performance.now(),acc=0,fps=60,simMs=0,renderMs=0,lastStats=0,audioCtx=null,lastReactionSound=0,lastInspection=null;
let brushSize='M',eraserSize='M';
const BRUSH_PRESETS={S:{count:.55,spread:.7,label:'Brush S'},M:{count:1,spread:1,label:'Brush M'},L:{count:1.65,spread:1.35,label:'Brush L'},XL:{count:2.5,spread:1.75,label:'Brush XL'}};
const ERASER_PRESETS={S:.32,M:.58,L:.95,XL:1.4};
const canvas=$('scene'); const nozzle=document.createElement('div');nozzle.className='nozzle';document.body.append(nozzle);
const app={sim,get selectedMaterialId(){return selectedMaterialId},get seed(){return seed},get graphics(){return renderer?.getGraphicsSettings?.()}};

function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1400);}
function haptic(ms=12){navigator.vibrate?.(ms);}
function allocateUserMaterialId(){if(nextMaterialId>=10000)nextMaterialId=1;while(sim.materials.has(nextMaterialId)&&nextMaterialId<10000)nextMaterialId++;if(nextMaterialId>=10000)throw new Error('Material palette is full');return nextMaterialId++;}
function addMaterial(s=seed){const m=generateMaterial(s,allocateUserMaterialId());m.reusable=true;sim.registerMaterial(m);selectedMaterialId=m.id;refreshMaterialSelect();syncMaterialUI();return m;}
function selected(){return sim.materials.get(selectedMaterialId);}
function reusableMaterials(){return [...sim.materials.values()].filter(m=>m.reusable!==false);}
function refreshMaterialSelect(){const sel=$('materialSelect');sel.innerHTML='';for(const m of reusableMaterials()){const o=document.createElement('option');o.value=String(m.id);o.textContent=m.name;sel.append(o);}if(sim.materials.has(selectedMaterialId)&&sim.materials.get(selectedMaterialId).reusable!==false)sel.value=String(selectedMaterialId);}
const materialFields=['opacity','density','viscosity','miscibility','cohesion','temperature','heatCapacity','thermalConductivity','meltingTemperature','boilingTemperature','volatility','reactionPotential'];
function syncMaterialUI(){const m=selected();if(!m)return;$('color').value=m.color;for(const f of materialFields)$(f).value=String(m[f]);$('matName').textContent=m.name;$('matPhaseHint').textContent=`ρ ${m.density.toFixed(2)} · μ ${m.viscosity.toFixed(2)} · mix ${m.miscibility.toFixed(2)} · T ${m.temperature.toFixed(2)}`;const sw=$('materialPreview').querySelector('span');sw.style.background=m.color;sw.style.color=m.color;sw.style.opacity=String(m.opacity);$('seedInput').value=String(m.seed);}
function applyMaterialField(field,value){const m=selected();if(!m)return;m[field]=value;if(field==='color')m.color=value;const arrMap={opacity:'opacity',density:'baseDensity',viscosity:'viscosity',miscibility:'miscibility',cohesion:'cohesion',temperature:'temperature',heatCapacity:'heatCapacity',thermalConductivity:'thermalConductivity',meltingTemperature:'meltingTemperature',boilingTemperature:'boilingTemperature',volatility:'volatility',reactionPotential:'reactionPotential'};const arr=arrMap[field]?sim.ps[arrMap[field]]:null;if(arr)for(let i=0;i<sim.ps.count;i++)if(sim.ps.materialId[i]===m.id){arr[i]=Number(value);if(field==='density')sim.ps.density[i]=sim.ps.effectiveDensityAt(i);}if(field==='color'){const n=parseInt(value.slice(1),16),r=((n>>16)&255)/255,g=((n>>8)&255)/255,b=(n&255)/255;for(let i=0;i<sim.ps.count;i++)if(sim.ps.materialId[i]===m.id){sim.ps.r[i]=r;sim.ps.g[i]=g;sim.ps.b[i]=b;}}syncMaterialUI();saveSetup(app);}
function randomize(kind='all'){const current=selected();if(!current)return;seed=Number($('seedInput').value)||Math.floor(Math.random()*1e9);const fresh=generateMaterial(seed,current.id);if(kind==='color'){current.color=fresh.color;}else if(kind==='physics'){for(const k of materialFields)if(k!=='opacity')current[k]=fresh[k];}else{Object.assign(current,fresh);}$('seedInput').value=String(seed);syncMaterialUI();haptic();saveSetup(app);}
function initMaterials(){const saved=loadSavedSetup(),restored=Boolean(saved?.materials?.length);if(restored){sim.materials.clear();for(const raw of saved.materials){const m=sanitizeMaterial(raw);m.reusable=raw.reusable!==false;sim.registerMaterial(m);nextMaterialId=Math.max(nextMaterialId,m.id+1);}selectedMaterialId=saved.selectedMaterialId&&sim.materials.has(saved.selectedMaterialId)?saved.selectedMaterialId:saved.materials[0].id;seed=saved.seed||1337;if(saved.box)sim.resizeBox(saved.box.width,saved.box.height,saved.box.depth);if(saved.rules)Object.assign(sim.rules,saved.rules);if(saved.env)Object.assign(sim.env,saved.env);if(saved.graphics)renderer?.configureGraphics(saved.graphics);}else addMaterial(seed);refreshMaterialSelect();syncMaterialUI();syncSettingsUI();syncGraphicsUI();return restored;}
function syncSettingsUI(){for(const f of ['miscibilityThreshold','baseMixingRate','mixingExponent','reactionStrength','condensationDensityThreshold','condensationCoolingCoefficient','thermalDiffusionRate'])$(f).value=String(sim.rules[f]);for(const f of ['environmentDensity','ambientTemperature','gravityStrength'])$(f).value=String(sim.env[f]);$('boxWidth').value=String(sim.env.box.width);$('boxHeight').value=String(sim.env.box.height);$('boxDepth').value=String(sim.env.box.depth);}
function syncToolUI(){
  for(const [id,m] of [['brushToolBtn','brush'],['eraserToolBtn','eraser'],['inspectToolBtn','inspect'],['cameraToolBtn','camera']])$(id)?.classList.toggle('primary',m===mode);
  for(const [id,m] of [['pourModeBtn','brush'],['heatModeBtn','heat'],['coolModeBtn','cool']])$(id)?.classList.toggle('primary',m===mode);
  const size=$('toolSize');if(size){size.disabled=mode==='camera'||mode==='inspect'||mode==='heat'||mode==='cool';size.value=mode==='eraser'?eraserSize:brushSize;}
  canvas.style.cursor=mode==='camera'?'grab':mode==='eraser'?'cell':mode==='inspect'?'help':'crosshair';
}
function setMode(next,quiet=false){mode=next;syncToolUI();if(!quiet)toast(mode==='camera'?'Camera — drag or pinch':mode==='eraser'?'Eraser — drag to remove':mode==='inspect'?'Inspector — tap material to sample':mode==='brush'?'Brush — camera locked to one-finger input':`${mode.toUpperCase()} — touch inside box`);}
function showInspection(sample){lastInspection=sample;const card=$('inspectionCard');if(!sample){card.hidden=true;return;}const dominant=sim.materials.get(sample.dominantMaterialId),m=sample.material,emergent=Boolean(dominant?.emergent);$('inspectionName').textContent=dominant?.name||'Local mixture';$('inspectionMeta').textContent=`${sample.count} particles · ${emergent?'emergent material':'local sample'} · ID ${sample.dominantMaterialId??'—'}`;$('inspectionSwatch').style.background=m.color;$('inspectionSwatch').style.color=m.color;$('inspectionProps').textContent=`ρ ${m.density.toFixed(2)} · μ ${m.viscosity.toFixed(2)} · mix ${m.miscibility.toFixed(2)} · T ${m.temperature.toFixed(2)} · opacity ${m.opacity.toFixed(2)}`;$('inspectionSaveName').value=(dominant?.name||'Captured mix').replace(/^Mix /,'Saved ');card.hidden=false;}
function inspectAt(point){const sample=sim.inspectMaterial(point,.8);if(!sample){showInspection(null);toast('No material in inspection radius');return;}showInspection(sample);haptic(8);}
function saveInspectedMaterial(){if(!lastInspection)return toast('Inspect a material first');const id=allocateUserMaterialId(),raw=structuredClone(lastInspection.material),dominant=sim.materials.get(lastInspection.dominantMaterialId),name=String($('inspectionSaveName').value||`Saved ${dominant?.name||'material'}`).slice(0,40),m=sanitizeMaterial({...raw,id,name,reusable:true,emergent:false,savedFromSimulation:true,sourceMaterialIds:dominant?.sourceMaterialIds||lastInspection.sourceMaterialIds});sim.registerMaterial(m);selectedMaterialId=m.id;refreshMaterialSelect();syncMaterialUI();saveSetup(app);toast(`${m.name} saved to palette`);haptic(18);}
function syncGraphicsUI(){if(!renderer)return;const g=renderer.getGraphicsSettings();$('renderRepresentation').value=g.representation;$('renderResolution').value=String(g.resolutionScale);$('renderFraction').value=String(g.renderFraction);$('cloudCellSize').value=String(g.cloudCellSize);$('effectsScale').value=String(g.effectsScale);$('resolutionValue').textContent=`${Math.round(g.resolutionScale*100)}%`;$('sampleValue').textContent=`${Math.round(g.renderFraction*100)}%`;$('cloudValue').textContent=g.cloudCellSize.toFixed(2);$('effectsValue').textContent=`${Math.round(g.effectsScale*100)}%`;}
function applyGraphicsPreset(name){if(name==='CUSTOM')return;renderer.applyGraphicsPreset(name);syncGraphicsUI();saveSetup(app);toast(`Graphics: ${name}`);}
function applyManualGraphics(){renderer.configureGraphics({representation:$('renderRepresentation').value,resolutionScale:Number($('renderResolution').value),renderFraction:Number($('renderFraction').value),cloudCellSize:Number($('cloudCellSize').value),effectsScale:Number($('effectsScale').value)});$('graphicsPreset').value='CUSTOM';syncGraphicsUI();saveSetup(app);}
function screenToBox(clientX,clientY){const rect=canvas.getBoundingClientRect();const nx=(clientX-rect.left)/rect.width-.5,ny=(clientY-rect.top)/rect.height-.5;const b=sim.env.box;return {x:Math.max(-b.width*.45,Math.min(b.width*.45,nx*b.width*1.3)),y:Math.max(-b.height*.45,Math.min(b.height*.45,-ny*b.height*1.2)),z:0};}
function interactAt(e,continuous=false){
  const fallback=screenToBox(e.clientX,e.clientY),picked=mode==='brush'||mode==='camera'?null:renderer?.pickParticle?.(e.clientX,e.clientY,86),p=picked?{x:picked.x,y:picked.y,z:picked.z}:fallback;
  nozzle.style.left=`${e.clientX}px`;nozzle.style.top=`${e.clientY}px`;nozzle.classList.add('show');nozzle.dataset.mode=mode;
  if(mode==='brush'){const volume=Number($('volume').value),preset=BRUSH_PRESETS[brushSize];const base=continuous?Math.max(2,Math.round(volume/8)):Math.max(4,Math.round(volume/3));const m=selected();if(m)sim.emit(m.id,p,Math.max(1,Math.round(base*preset.count)),m.temperature,preset.spread);}
  else if(mode==='eraser')sim.erase(p,ERASER_PRESETS[eraserSize]);
  else if(mode==='inspect'){if(!continuous)inspectAt(p);}
  else if(mode==='heat'||mode==='cool'){const amount=(mode==='heat'?1:-1)*(continuous?.05:.14),result=sim.applyHeat(p,1.4,amount);if(!continuous&&result.affected===0)toast('No material under thermal tool');}
}
function loadPreset(key){const p=PRESETS[key];if(!p)return;sim.reset();sim.materials.clear();for(const raw of p.materials){const m=sanitizeMaterial(structuredClone(raw));sim.registerMaterial(m);nextMaterialId=Math.max(nextMaterialId,m.id+1);}selectedMaterialId=p.materials[0].id;refreshMaterialSelect();syncMaterialUI();const b=sim.env.box;if(key==='mixing'||key==='shock'){sim.emit(p.materials[0].id,{x:-b.width*.22,y:b.height*.24,z:0},220,p.materials[0].temperature);sim.emit(p.materials[1].id,{x:b.width*.22,y:b.height*.24,z:0},220,p.materials[1].temperature);}else if(key==='layers'){sim.emit(p.materials[0].id,{x:0,y:b.height*.22,z:0},220);sim.emit(p.materials[1].id,{x:0,y:b.height*.35,z:0},220);}else if(key==='rain'){sim.env.ambientTemperature=.24;sim.rules.condensationDensityThreshold=.46;sim.rules.condensationCoolingCoefficient=.72;sim.emit(p.materials[0].id,{x:0,y:-b.height*.35,z:0},450,p.materials[0].temperature);}else if(key==='freeze'){sim.emit(p.materials[0].id,{x:0,y:.4,z:0},420,p.materials[0].temperature);}renderer?.updateBox();syncSettingsUI();toast(p.name);haptic(20);saveSetup(app);}
function applySetup(data){if(!data||data.version!==1)throw new Error('Unsupported setup');sim.reset();sim.materials.clear();for(const raw of data.materials||[]){const m=sanitizeMaterial(raw);sim.registerMaterial(m);nextMaterialId=Math.max(nextMaterialId,m.id+1);}if(!sim.materials.size)addMaterial(seed);selectedMaterialId=data.selectedMaterialId&&sim.materials.has(data.selectedMaterialId)?data.selectedMaterialId:[...sim.materials.keys()][0];if(data.box)sim.resizeBox(data.box.width,data.box.height,data.box.depth);if(data.rules)Object.assign(sim.rules,data.rules);if(data.env)Object.assign(sim.env,data.env);if(data.graphics)renderer.configureGraphics(data.graphics);seed=data.seed||seed;refreshMaterialSelect();syncMaterialUI();syncSettingsUI();syncGraphicsUI();renderer.updateBox();saveSetup(app);}
function bindUI(){
  const sheet=$('sheet'),toggle=$('sheetToggleBtn');
  const setSheetOpen=open=>{sheet.classList.toggle('collapsed',!open);toggle.classList.toggle('primary',open);toggle.textContent=open?'Hide':'Controls';toggle.setAttribute('aria-expanded',String(open));};
  setSheetOpen(false);toggle.onclick=()=>setSheetOpen(sheet.classList.contains('collapsed'));
  document.querySelectorAll('.tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===btn.dataset.tab));setSheetOpen(true);}));
  $('materialSelect').onchange=e=>{selectedMaterialId=Number(e.target.value);syncMaterialUI();};$('addMaterialBtn').onclick=()=>{seed=(seed+1)>>>0;addMaterial(seed);saveSetup(app);};$('randomizeBtn').onclick=()=>randomize('all');$('randomColorBtn').onclick=()=>randomize('color');$('randomPhysicsBtn').onclick=()=>randomize('physics');
  $('color').oninput=e=>applyMaterialField('color',e.target.value);for(const f of materialFields)$(f).oninput=e=>applyMaterialField(f,Number(e.target.value));
  $('brushToolBtn').onclick=()=>setMode('brush');$('eraserToolBtn').onclick=()=>setMode('eraser');$('inspectToolBtn').onclick=()=>setMode('inspect');$('cameraToolBtn').onclick=()=>setMode('camera');
  $('toolSize').onchange=e=>{if(mode==='eraser')eraserSize=e.target.value;else brushSize=e.target.value;syncToolUI();toast(mode==='eraser'?`Eraser ${eraserSize}`:`Brush ${brushSize}`);};
  $('pourModeBtn').onclick=()=>setMode('brush');$('heatModeBtn').onclick=()=>setMode('heat');$('coolModeBtn').onclick=()=>setMode('cool');$('resetViewBtn').onclick=()=>{renderer.setOrbit(.65,.35,12);toast('Camera reset');};
  document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>loadPreset(b.dataset.preset));
  for(const f of ['miscibilityThreshold','baseMixingRate','mixingExponent','reactionStrength','condensationDensityThreshold','condensationCoolingCoefficient','thermalDiffusionRate'])$(f).oninput=e=>{sim.rules[f]=Number(e.target.value);saveSetup(app);};
  for(const f of ['environmentDensity','ambientTemperature'])$(f).oninput=e=>{sim.env[f]=Number(e.target.value);saveSetup(app);};$('gravityStrength').oninput=e=>{sim.env.gravityStrength=Number(e.target.value);saveSetup(app);};
  const resize=()=>{sim.resizeBox(Number($('boxWidth').value),Number($('boxHeight').value),Number($('boxDepth').value));renderer.updateBox();saveSetup(app);};for(const f of ['boxWidth','boxHeight','boxDepth'])$(f).onchange=resize;
  $('pauseBtn').onclick=()=>{sim.paused=!sim.paused;$('pauseBtn').textContent=sim.paused?'Resume':'Pause';};$('resetBtn').onclick=()=>{sim.reset();toast('Simulation reset');};
  $('motionBtn').onclick=async()=>{const ok=await gravity.enableDevice();if(ok){$('motionBtn').textContent='Motion enabled';toast('Motion controls active — calibrate neutral pose');}else{gravity.useManual();toast('Motion unavailable — manual gravity active');}};$('calibrateBtn').onclick=()=>{gravity.calibrate();toast('Orientation calibrated');};$('orientationResetBtn').onclick=()=>{gravity.reset();toast('Orientation reset');};$('sensitivity').oninput=e=>{gravity.manual.sensitivity=gravity.device.sensitivity=Number(e.target.value);};
  $('quality').onchange=e=>quality.setMode(e.target.value);document.querySelectorAll('[data-debug]').forEach(b=>b.onclick=()=>renderer.debugMode=b.dataset.debug);$('graphicsPreset').onchange=e=>applyGraphicsPreset(e.target.value);for(const id of ['renderRepresentation','renderResolution','renderFraction','cloudCellSize','effectsScale'])$(id).oninput=applyManualGraphics;$('saveInspectionBtn').onclick=saveInspectedMaterial;$('closeInspectionBtn').onclick=()=>showInspection(null);
  $('exportBtn').onclick=()=>exportSetup(app);$('importInput').onchange=async e=>{try{const data=await importSetupFile(e.target.files[0]);applySetup(data);toast('Setup imported');}catch(err){toast(`Import failed: ${err.message}`);}};
  syncToolUI();
}
function bindCanvas(){
  const active=new Map();let gesture=null,single=null,pendingTouch=null,suppressSingle=false;
  const clearPending=()=>{if(pendingTouch){clearTimeout(pendingTouch.timer);pendingTouch=null;}};
  const beginTwoFinger=()=>{clearPending();suppressSingle=true;const pts=[...active.values()];if(pts.length<2)return;const a=pts[0],b=pts[1];gesture={startMid:pointerMidpoint(a,b),startPinch:pointerDistance(a,b),yaw:renderer.yaw,pitch:renderer.pitch,distance:renderer.distance};single=null;nozzle.classList.remove('show');};
  const updateTwoFinger=()=>{const pts=[...active.values()];if(pts.length<2||!gesture)return;const a=pts[0],b=pts[1],mid=pointerMidpoint(a,b),pinch=pointerDistance(a,b);renderer.setOrbit(gesture.yaw+(mid.x-gesture.startMid.x)*.0075,gesture.pitch+(mid.y-gesture.startMid.y)*.0065,pinchCameraDistance(gesture.distance,gesture.startPinch,pinch));};
  const startSingle=e=>{single={id:e.pointerId,x:e.clientX,y:e.clientY,yaw:renderer.yaw,pitch:renderer.pitch,distance:renderer.distance};if(mode!=='camera')interactAt(e,false);};
  canvas.addEventListener('pointerdown',e=>{ensureAudio();canvas.setPointerCapture(e.pointerId);active.set(e.pointerId,{x:e.clientX,y:e.clientY,pointerType:e.pointerType});if(active.size>=2){beginTwoFinger();return;}if(e.pointerType==='touch'&&mode!=='camera'){clearPending();pendingTouch={id:e.pointerId,timer:setTimeout(()=>{if(active.size===1&&active.has(e.pointerId)){startSingle(e);pendingTouch=null;}},70)};}else startSingle(e);});
  canvas.addEventListener('pointermove',e=>{if(!active.has(e.pointerId))return;active.set(e.pointerId,{x:e.clientX,y:e.clientY,pointerType:e.pointerType});if(active.size>=2){if(!gesture)beginTwoFinger();updateTwoFinger();return;}if(suppressSingle||pendingTouch?.id===e.pointerId)return;if(!single||single.id!==e.pointerId)return;if(mode==='camera'){renderer.setOrbit(single.yaw+(e.clientX-single.x)*.009,single.pitch+(e.clientY-single.y)*.008,single.distance);}else interactAt(e,true);});
  const finish=e=>{if(pendingTouch?.id===e.pointerId){clearTimeout(pendingTouch.timer);pendingTouch=null;if(active.size===1&&mode!=='camera')interactAt(e,false);}active.delete(e.pointerId);if(active.size<2)gesture=null;if(active.size===1&&!suppressSingle){const [id,p]=active.entries().next().value;single={id,x:p.x,y:p.y,yaw:renderer.yaw,pitch:renderer.pitch,distance:renderer.distance};}else if(active.size===0){single=null;suppressSingle=false;nozzle.classList.remove('show');}};
  canvas.addEventListener('pointerup',finish);canvas.addEventListener('pointercancel',finish);
  canvas.addEventListener('wheel',e=>{e.preventDefault();renderer.setOrbit(renderer.yaw,renderer.pitch,renderer.distance+Math.sign(e.deltaY));},{passive:false});
  const pad=$('manualPad'),dot=$('manualDot');const padMove=e=>{const r=pad.getBoundingClientRect(),x=Math.max(-1,Math.min(1,(e.clientX-(r.left+r.width/2))/(r.width/2))),z=Math.max(-1,Math.min(1,(e.clientY-(r.top+r.height/2))/(r.height/2)));gravity.useManual();gravity.manual.setTilt(x,z);dot.style.left=`calc(${50+x*42}% - 9px)`;dot.style.top=`calc(${50+z*36}% - 9px)`;};pad.addEventListener('pointerdown',e=>{pad.setPointerCapture(e.pointerId);padMove(e)});pad.addEventListener('pointermove',e=>{if(e.buttons)padMove(e)});
}
function ensureAudio(){if(!audioCtx){const AC=globalThis.AudioContext||globalThis.webkitAudioContext;if(AC)audioCtx=new AC();}if(audioCtx?.state==='suspended')audioCtx.resume().catch(()=>{});}
function reactionSound(now){if(!audioCtx||now-lastReactionSound<260||sim.reactions.eventCount===0)return;let intensity=0;for(let i=0;i<sim.reactions.eventCount;i++)intensity=Math.max(intensity,sim.reactions.eventIntensity[i]);if(intensity<.58)return;lastReactionSound=now;const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.value=120+intensity*420;gain.gain.setValueAtTime(.0001,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.025*intensity,audioCtx.currentTime+.008);gain.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.09);osc.connect(gain).connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+.1);}
function updateStats(now){if(now-lastStats<250)return;lastStats=now;const pc=sim.ps.phaseCounts(),g=sim.gravity,gr=renderer.getGraphicsSettings();$('stats').textContent=`particles ${sim.ps.count}/${sim.ps.capacity} · drawn ${renderer.drawCount||0}\nFPS ${fps.toFixed(0)} · sim ${simMs.toFixed(2)} ms · render ${renderMs.toFixed(2)} ms\nmaterials ${reusableMaterials().length} saved + ${sim.stats.generatedMaterials} emergent · reactions ${sim.stats.reactions}\nsolid ${pc[0]} · liquid ${pc[1]} · gas ${pc[2]}\ng ${g.x.toFixed(2)} ${g.y.toFixed(2)} ${g.z.toFixed(2)}\nphysics ${quality.mode}/${sim.iterations} · graphics ${gr.representation} ${Math.round(gr.resolutionScale*100)}%`;$('gravityHud').textContent=`g ${g.x.toFixed(2)} ${g.y.toFixed(2)} ${g.z.toFixed(2)}`;$('status').textContent=gr.representation==='CLOUDS'?'CLOUDS':quality.mode;}
function loop(now){const frame=Math.min(.05,(now-last)/1000);last=now;fps=fps*.92+(1/Math.max(.001,frame))*.08;const gv=gravity.getGravity();sim.setGravity(gv.x,gv.y,gv.z);acc+=frame;const fixed=1/40;let steps=0;const st=performance.now();while(acc>=fixed&&steps<3){sim.step(fixed);acc-=fixed;steps++;}simMs=performance.now()-st;const rt=performance.now();renderer.update(frame);renderer.render();renderMs=performance.now()-rt;reactionSound(now);const qm=quality.sample(frame*1000);if(qm){sim.iterations=quality.iterations;toast(`Adaptive quality: ${qm}`);}else sim.iterations=quality.iterations;updateStats(now);requestAnimationFrame(loop);}
async function boot(){renderer=new SceneRenderer(canvas,sim);const restored=initMaterials();bindUI();bindCanvas();addEventListener('resize',()=>renderer.resize());if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});if(!restored)loadPreset('mixing');requestAnimationFrame(loop);}
boot().catch(err=>{console.error(err);document.body.innerHTML=`<pre style="padding:20px;color:#ff9b9b">Startup failed\n${err.stack||err}</pre>`;});
