import { SimulationEngine } from '../simulation/SimulationEngine.mjs';
import { generateMaterial } from '../materials/MaterialGenerator.mjs';
import { sanitizeMaterial } from '../materials/MaterialDefinition.mjs';
import { PRESETS } from '../materials/Presets.mjs';
import { GravityController } from '../sensors/GravityInputProvider.mjs';
import { AdaptiveQuality } from '../performance/AdaptiveQuality.mjs';
import { saveSetup, loadSavedSetup, exportSetup, importSetupFile } from './storage.mjs';
import { SceneRenderer } from '../rendering/SceneRenderer.mjs';
import { PlanarRenderer } from '../rendering/PlanarRenderer.mjs';
import { pointerDistance, pointerMidpoint, pinchCameraDistance } from './gestureMath.mjs';

const $=id=>document.getElementById(id);
const sim=new SimulationEngine(6000),gravity=new GravityController(),quality=new AdaptiveQuality();
let seed=1337,nextMaterialId=1,selectedMaterialId=0,mode='brush',viewMode='3D',renderer,renderer3d,renderer2d,last=performance.now(),acc=0,fps=60,simMs=0,renderMs=0,lastStats=0,audioCtx=null,lastReactionSound=0,lastInspection=null;
let brushSize='M',eraserSize='M',moldSize='M';
const BRUSH_PRESETS={S:{count:.55,spread:.7},M:{count:1,spread:1},L:{count:1.65,spread:1.35},XL:{count:2.5,spread:1.75}};
const ERASER_PRESETS={S:.32,M:.58,L:.95,XL:1.4},THERMAL_SCALE_MAX=1.4;
const canvas3d=$('scene'),canvas2d=$('scene2d');let canvas=canvas3d;
const nozzle=document.createElement('div');nozzle.className='nozzle';document.body.append(nozzle);
const app={sim,get selectedMaterialId(){return selectedMaterialId},get seed(){return seed},get graphics(){return renderer?.getGraphicsSettings?.()},get graphicsByMode(){return {'3D':renderer3d?.getGraphicsSettings?.(),'2D':renderer2d?.getGraphicsSettings?.()};},get viewMode(){return viewMode;}};

function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1500);}
function haptic(ms=12){navigator.vibrate?.(ms);}
function freshSeed(){const a=new Uint32Array(1);if(globalThis.crypto?.getRandomValues)globalThis.crypto.getRandomValues(a);else a[0]=((Date.now()^Math.floor(Math.random()*0xffffffff))>>>0);return a[0]||1;}
function allocateUserMaterialId(){if(nextMaterialId>=10000)nextMaterialId=1;while(sim.materials.has(nextMaterialId)&&nextMaterialId<10000)nextMaterialId++;if(nextMaterialId>=10000)throw new Error('Material palette is full');return nextMaterialId++;}
function selected(){return sim.materials.get(selectedMaterialId);}
function reusableMaterials(){return [...sim.materials.values()].filter(m=>m.reusable!==false);}
function addMaterial(s=freshSeed()){const m=generateMaterial(s,allocateUserMaterialId());m.reusable=true;sim.registerMaterial(m);selectedMaterialId=m.id;seed=s;refreshMaterialSelect();syncMaterialUI();return m;}
function refreshMaterialSelect(){const sel=$('materialSelect');sel.innerHTML='';for(const m of reusableMaterials()){const o=document.createElement('option');o.value=String(m.id);o.textContent=m.name;sel.append(o);}if(sim.materials.has(selectedMaterialId)&&sim.materials.get(selectedMaterialId).reusable!==false)sel.value=String(selectedMaterialId);}

const materialFields=['opacity','density','viscosity','miscibility','cohesion','heatCapacity','thermalConductivity','meltingTemperature','boilingTemperature','volatility','reactionPotential','reactionHeat','crystallinity','solidSubdivision','electricalConductivity','electricPotential','combustionTemperature'];
const particleFieldMap={opacity:'opacity',density:'baseDensity',viscosity:'viscosity',miscibility:'miscibility',cohesion:'cohesion',heatCapacity:'heatCapacity',thermalConductivity:'thermalConductivity',meltingTemperature:'meltingTemperature',boilingTemperature:'boilingTemperature',volatility:'volatility',reactionPotential:'reactionPotential',reactionHeat:'reactionHeat',crystallinity:'crystallinity',solidSubdivision:'solidSubdivision',electricalConductivity:'electricalConductivity',electricPotential:'electricPotential',combustionTemperature:'combustionTemperature'};
function syncMaterialParticles(m){const n=parseInt(m.color.slice(1),16),r=((n>>16)&255)/255,g=((n>>8)&255)/255,b=(n&255)/255;for(let i=0;i<sim.ps.count;i++)if(sim.ps.materialId[i]===m.id){sim.ps.r[i]=r;sim.ps.g[i]=g;sim.ps.b[i]=b;for(const [field,arrayName] of Object.entries(particleFieldMap))sim.ps[arrayName][i]=Number(m[field]);sim.ps.density[i]=sim.ps.effectiveDensityAt(i);if(m.solidSubdivision>=.55)sim.ps.solidBodyId[i]=0;}}
function materialTemperatureStats(){let sum=0,n=0;for(let i=0;i<sim.ps.count;i++)if(sim.ps.materialId[i]===selectedMaterialId){sum+=sim.ps.temperature[i];n++;}return n?{temperature:sum/n,count:n,ambient:false}:{temperature:sim.env.ambientTemperature,count:0,ambient:true};}
function updateThermometer(){
  const el=$('materialTemperature'),fill=$('thermometerFill'),m=selected();if(!el||!fill||!m)return;const s=materialTemperatureStats(),t=Math.max(0,Math.min(THERMAL_SCALE_MAX,s.temperature));fill.style.width=`${Math.min(100,t/THERMAL_SCALE_MAX*100)}%`;el.textContent=`T ${s.temperature.toFixed(2)} · ${s.ambient?'ambient':'scene avg'}`;
  const marker=(id,value,label)=>{const node=$(id);if(!node)return;node.style.left=`${Math.max(0,Math.min(100,value/THERMAL_SCALE_MAX*100))}%`;node.title=`${label} ${value.toFixed(2)}`;node.setAttribute('aria-label',`${label} ${value.toFixed(2)}`);};marker('meltMarker',m.meltingTemperature,'Melt');marker('boilMarker',m.boilingTemperature,'Boil');marker('burnMarker',m.combustionTemperature,'Burn');
  if($('meltReadout'))$('meltReadout').textContent=`Melt ${m.meltingTemperature.toFixed(2)}`;if($('boilReadout'))$('boilReadout').textContent=`Boil ${m.boilingTemperature.toFixed(2)}`;if($('burnReadout'))$('burnReadout').textContent=`Burn ${m.combustionTemperature.toFixed(2)}`;
}
function syncMaterialUI(){const m=selected();if(!m)return;$('color').value=m.color;for(const f of materialFields)if($(f))$(f).value=String(m[f]);$('matName').textContent=m.name;$('matPhaseHint').textContent=`ρ ${m.density.toFixed(2)} · μ ${m.viscosity.toFixed(2)} · crystal ${m.crystallinity.toFixed(2)} · subdivision ${m.solidSubdivision.toFixed(2)}`;const sw=$('materialPreview').querySelector('span');sw.style.background=m.color;sw.style.color=m.color;sw.style.opacity=String(m.opacity);$('seedInput').value=String(m.seed);updateThermometer();}
function applyMaterialField(field,value){const m=selected();if(!m)return;if(field==='color')m.color=value;else m[field]=Number(value);syncMaterialParticles(m);syncMaterialUI();saveSetup(app);}
function randomize(kind='all'){const current=selected();if(!current)return;seed=freshSeed();const fresh=generateMaterial(seed,current.id),reusable=current.reusable!==false;if(kind==='color')current.color=fresh.color;else if(kind==='physics'){for(const k of materialFields)if(k!=='opacity')current[k]=fresh[k];}else Object.assign(current,fresh,{reusable});current.seed=seed;syncMaterialParticles(current);refreshMaterialSelect();syncMaterialUI();haptic();saveSetup(app);toast(kind==='color'?'Color randomized':kind==='physics'?'Physics randomized':'Material randomized');}

function initMaterials(){const saved=loadSavedSetup(),restored=Boolean(saved?.materials?.length);if(restored){sim.materials.clear();for(const raw of saved.materials){const m=sanitizeMaterial(raw);m.reusable=raw.reusable!==false;sim.registerMaterial(m);nextMaterialId=Math.max(nextMaterialId,m.id+1);}selectedMaterialId=saved.selectedMaterialId&&sim.materials.has(saved.selectedMaterialId)?saved.selectedMaterialId:saved.materials[0].id;seed=saved.seed||1337;viewMode=saved.viewMode==='2D'?'2D':'3D';sim.setDimensionMode(viewMode);if(saved.box)sim.resizeBox(saved.box.width,saved.box.height,saved.box.depth);if(saved.rules)Object.assign(sim.rules,saved.rules);if(saved.env)Object.assign(sim.env,saved.env);if(saved.molds)sim.molds.restore(saved.molds);if(saved.graphicsByMode){if(saved.graphicsByMode['3D'])renderer3d.configureGraphics(saved.graphicsByMode['3D']);if(saved.graphicsByMode['2D'])renderer2d.configureGraphics(saved.graphicsByMode['2D']);}else if(saved.graphics){renderer3d.configureGraphics(saved.graphics);renderer2d.configureGraphics(saved.graphics);}}else addMaterial(seed);refreshMaterialSelect();syncMaterialUI();syncSettingsUI();setViewMode(viewMode,true);syncGraphicsUI();return restored;}
function syncSettingsUI(){for(const f of ['miscibilityThreshold','baseMixingRate','mixingExponent','reactionStrength','thermalReactionThreshold','thermalReactionStrength','condensationDensityThreshold','condensationCoolingCoefficient','thermalDiffusionRate','electricalConductionRate','combustionRate','combustionHeatScale'])if($(f))$(f).value=String(sim.rules[f]);for(const f of ['environmentDensity','ambientTemperature','gravityStrength'])$(f).value=String(sim.env[f]);$('boxWidth').value=String(sim.env.box.width);$('boxHeight').value=String(sim.env.box.height);$('boxDepth').value=String(sim.env.box.depth);updateThermometer();}
function syncToolUI(){for(const [id,m] of [['brushToolBtn','brush'],['eraserToolBtn','eraser'],['inspectToolBtn','inspect'],['moldToolBtn','mold'],['cameraToolBtn','camera']])$(id)?.classList.toggle('primary',m===mode);for(const [id,m] of [['pourModeBtn','brush'],['heatModeBtn','heat'],['coolModeBtn','cool']])$(id)?.classList.toggle('primary',m===mode);const size=$('toolSize');if(size){size.disabled=['camera','inspect','heat','cool'].includes(mode);size.value=mode==='eraser'?eraserSize:mode==='mold'?moldSize:brushSize;}canvas.style.cursor=mode==='camera'?'grab':mode==='eraser'?'cell':mode==='inspect'?'help':'crosshair';}
function setMode(next,quiet=false){mode=next;syncToolUI();if(!quiet)toast(mode==='camera'?'View — drag or pinch':mode==='eraser'?'Erase — drag to remove':mode==='inspect'?'Inspect — tap matter':mode==='mold'?'Mold — tap to place an open mold':mode==='brush'?'Draw — one finger places matter':`${mode.toUpperCase()} — touch matter`);}
function showInspection(sample){lastInspection=sample;const card=$('inspectionCard');if(!sample){card.hidden=true;return;}const dominant=sim.materials.get(sample.dominantMaterialId),m=sample.material,emergent=Boolean(dominant?.emergent);$('inspectionName').textContent=dominant?.name||'Local mixture';$('inspectionMeta').textContent=`${sample.count} particles · ${emergent?'emergent material':'local sample'} · ID ${sample.dominantMaterialId??'—'}`;$('inspectionSwatch').style.background=m.color;$('inspectionSwatch').style.color=m.color;$('inspectionProps').textContent=`ρ ${m.density.toFixed(2)} · μ ${m.viscosity.toFixed(2)} · T ${sample.temperature.toFixed(2)} · crystal ${m.crystallinity.toFixed(2)} · subdivision ${m.solidSubdivision.toFixed(2)} · σ ${m.electricalConductivity.toFixed(2)} · V ${m.electricPotential.toFixed(2)} · ignite ${m.combustionTemperature.toFixed(2)}`;$('inspectionSaveName').value=(dominant?.name||'Captured mix').replace(/^Mix /,'Saved ');card.hidden=false;}
function inspectAt(point){const sample=sim.inspectMaterial(point,.8);if(!sample){showInspection(null);toast('No material in inspection radius');return;}showInspection(sample);haptic(8);}
function saveInspectedMaterial(){if(!lastInspection)return toast('Inspect a material first');const id=allocateUserMaterialId(),raw=structuredClone(lastInspection.material),dominant=sim.materials.get(lastInspection.dominantMaterialId),name=String($('inspectionSaveName').value||`Saved ${dominant?.name||'material'}`).slice(0,40),m=sanitizeMaterial({...raw,id,name,reusable:true,emergent:false,savedFromSimulation:true,sourceMaterialIds:dominant?.sourceMaterialIds||lastInspection.sourceMaterialIds});sim.registerMaterial(m);selectedMaterialId=m.id;refreshMaterialSelect();syncMaterialUI();saveSetup(app);toast(`${m.name} saved`);haptic(18);}

function syncGraphicsUI(){if(!renderer)return;const g=renderer.getGraphicsSettings();$('renderRepresentation').value=g.representation;$('renderResolution').value=String(g.resolutionScale);$('renderFraction').value=String(g.renderFraction);$('cloudCellSize').value=String(g.cloudCellSize);$('effectsScale').value=String(g.effectsScale);$('resolutionValue').textContent=`${Math.round(g.resolutionScale*100)}%`;$('sampleValue').textContent=`${Math.round(g.renderFraction*100)}%`;$('cloudValue').textContent=g.cloudCellSize.toFixed(2);$('effectsValue').textContent=`${Math.round(g.effectsScale*100)}%`;}
function applyGraphicsPreset(name){if(name==='CUSTOM')return;renderer3d.applyGraphicsPreset(name);renderer2d.applyGraphicsPreset(name);syncGraphicsUI();saveSetup(app);toast(`Display: ${name}`);}
function applyManualGraphics(){const next={representation:$('renderRepresentation').value,resolutionScale:Number($('renderResolution').value),renderFraction:Number($('renderFraction').value),cloudCellSize:Number($('cloudCellSize').value),effectsScale:Number($('effectsScale').value)};renderer.configureGraphics(next);$('graphicsPreset').value='CUSTOM';syncGraphicsUI();saveSetup(app);}
function resetView(){const b=sim.env.box;if(viewMode==='2D')renderer.setOrbit(0,0,12);else renderer.setOrbit(.65,.35,Math.max(12,Math.max(b.width,b.height,b.depth)*1.45));toast('View reset');}
function setViewMode(next,quiet=false){viewMode=next==='2D'?'2D':'3D';sim.setDimensionMode(viewMode);renderer=viewMode==='2D'?renderer2d:renderer3d;canvas=viewMode==='2D'?canvas2d:canvas3d;canvas3d.hidden=viewMode==='2D';canvas2d.hidden=viewMode!=='2D';$('view2dBtn')?.classList.toggle('active',viewMode==='2D');$('view3dBtn')?.classList.toggle('active',viewMode==='3D');$('boxDepth').disabled=viewMode==='2D';$('boxWidth').max='60';$('boxHeight').max='60';renderer.resize(true);if(viewMode==='3D')renderer3d.updateBox();syncToolUI();syncGraphicsUI();if(!quiet){toast(viewMode==='2D'?'2D — planar fast mode':'3D — depth placement restored');saveSetup(app);}}
function screenToBox(clientX,clientY){const world=renderer?.screenToWorld?.(clientX,clientY),b=sim.env.box;if(world){return{x:Math.max(-b.width*.47,Math.min(b.width*.47,world.x)),y:Math.max(-b.height*.47,Math.min(b.height*.47,world.y)),z:viewMode==='2D'?0:Math.max(-b.depth*.47,Math.min(b.depth*.47,world.z||0))};}const rect=canvas.getBoundingClientRect(),nx=(clientX-rect.left)/rect.width-.5,ny=(clientY-rect.top)/rect.height-.5;return{x:Math.max(-b.width*.47,Math.min(b.width*.47,nx*b.width*1.3)),y:Math.max(-b.height*.47,Math.min(b.height*.47,-ny*b.height*1.2)),z:0};}
function interactAt(e,continuous=false){const fallback=screenToBox(e.clientX,e.clientY),picked=['brush','camera','mold'].includes(mode)?null:renderer?.pickParticle?.(e.clientX,e.clientY,86),p=picked?{x:picked.x,y:picked.y,z:picked.z}:fallback;nozzle.style.left=`${e.clientX}px`;nozzle.style.top=`${e.clientY}px`;nozzle.classList.add('show');nozzle.dataset.mode=mode;if(mode==='brush'){const volume=Number($('volume').value),preset=BRUSH_PRESETS[brushSize],base=continuous?Math.max(2,Math.round(volume/8)):Math.max(4,Math.round(volume/3)),m=selected();if(m)sim.emit(m.id,p,Math.max(1,Math.round(base*preset.count)),undefined,preset.spread);}else if(mode==='eraser')sim.erase(p,ERASER_PRESETS[eraserSize]);else if(mode==='inspect'){if(!continuous)inspectAt(p);}else if(mode==='mold'&&!continuous){sim.addMold(p,moldSize);renderer3d.updateBox();saveSetup(app);toast(`Mold ${moldSize} placed`);haptic(14);}else if(mode==='heat'||mode==='cool'){const amount=(mode==='heat'?1:-1)*(continuous?.05:.14),result=sim.applyHeat(p,1.4,amount);if(!continuous&&result.affected===0)toast('No material under thermal tool');}}

function loadPreset(key){const p=PRESETS[key];if(!p)return;sim.reset();sim.materials.clear();for(const raw of p.materials){const m=sanitizeMaterial(structuredClone(raw));sim.registerMaterial(m);nextMaterialId=Math.max(nextMaterialId,m.id+1);}selectedMaterialId=p.materials[0].id;refreshMaterialSelect();syncMaterialUI();const b=sim.env.box,temps=p.spawnTemperatures||[];if(key==='mixing'||key==='shock'){sim.emit(p.materials[0].id,{x:-b.width*.22,y:b.height*.24,z:-b.depth*.16},220,temps[0]);sim.emit(p.materials[1].id,{x:b.width*.22,y:b.height*.24,z:b.depth*.16},220,temps[1]);}else if(key==='layers'){sim.emit(p.materials[0].id,{x:0,y:b.height*.22,z:-b.depth*.14},220);sim.emit(p.materials[1].id,{x:0,y:b.height*.35,z:b.depth*.14},220);}else if(key==='rain'){sim.env.ambientTemperature=.24;sim.rules.condensationDensityThreshold=.46;sim.rules.condensationCoolingCoefficient=.72;sim.emit(p.materials[0].id,{x:0,y:-b.height*.35,z:0},450,temps[0]);}else if(key==='freeze')sim.emit(p.materials[0].id,{x:0,y:.4,z:0},420,temps[0]);renderer3d?.updateBox();syncSettingsUI();toast(p.name);haptic(20);saveSetup(app);}
function applySetup(data){if(!data||data.version!==1)throw new Error('Unsupported setup');sim.reset();sim.materials.clear();for(const raw of data.materials||[]){const m=sanitizeMaterial(raw);sim.registerMaterial(m);nextMaterialId=Math.max(nextMaterialId,m.id+1);}if(!sim.materials.size)addMaterial(seed);selectedMaterialId=data.selectedMaterialId&&sim.materials.has(data.selectedMaterialId)?data.selectedMaterialId:[...sim.materials.keys()][0];viewMode=data.viewMode==='2D'?'2D':'3D';sim.setDimensionMode(viewMode);if(data.box)sim.resizeBox(data.box.width,data.box.height,data.box.depth);if(data.rules)Object.assign(sim.rules,data.rules);if(data.env)Object.assign(sim.env,data.env);if(data.molds)sim.molds.restore(data.molds);if(data.graphicsByMode){if(data.graphicsByMode['3D'])renderer3d.configureGraphics(data.graphicsByMode['3D']);if(data.graphicsByMode['2D'])renderer2d.configureGraphics(data.graphicsByMode['2D']);}else if(data.graphics){renderer3d.configureGraphics(data.graphics);renderer2d.configureGraphics(data.graphics);}seed=data.seed||seed;refreshMaterialSelect();syncMaterialUI();syncSettingsUI();setViewMode(viewMode,true);syncGraphicsUI();renderer3d.updateBox();saveSetup(app);}

let setSheetOpen=()=>{};
function bindUI(){
  const sheet=$('sheet'),toggle=$('sheetToggleBtn');setSheetOpen=open=>{sheet.classList.toggle('collapsed',!open);toggle.classList.toggle('primary',open);toggle.textContent=open?'×':'☰';toggle.setAttribute('aria-expanded',String(open));};setSheetOpen(matchMedia('(min-width:900px) and (pointer:fine)').matches);toggle.onclick=()=>setSheetOpen(sheet.classList.contains('collapsed'));
  document.querySelectorAll('.tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===btn.dataset.tab));setSheetOpen(true);}));
  $('materialSelect').onchange=e=>{selectedMaterialId=Number(e.target.value);syncMaterialUI();};$('addMaterialBtn').onclick=()=>{addMaterial();saveSetup(app);};$('randomizeBtn').onclick=()=>randomize('all');$('randomColorBtn').onclick=()=>randomize('color');$('randomPhysicsBtn').onclick=()=>randomize('physics');$('color').oninput=e=>applyMaterialField('color',e.target.value);for(const f of materialFields)if($(f))$(f).oninput=e=>applyMaterialField(f,Number(e.target.value));
  $('brushToolBtn').onclick=()=>setMode('brush');$('eraserToolBtn').onclick=()=>setMode('eraser');$('inspectToolBtn').onclick=()=>setMode('inspect');$('moldToolBtn').onclick=()=>setMode('mold');$('cameraToolBtn').onclick=()=>setMode('camera');$('toolSize').onchange=e=>{if(mode==='eraser')eraserSize=e.target.value;else if(mode==='mold')moldSize=e.target.value;else brushSize=e.target.value;syncToolUI();};$('pourModeBtn').onclick=()=>setMode('brush');$('heatModeBtn').onclick=()=>setMode('heat');$('coolModeBtn').onclick=()=>setMode('cool');$('view2dBtn').onclick=()=>setViewMode('2D');$('view3dBtn').onclick=()=>setViewMode('3D');$('resetViewBtn').onclick=resetView;document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>loadPreset(b.dataset.preset));
  for(const f of ['miscibilityThreshold','baseMixingRate','mixingExponent','reactionStrength','thermalReactionThreshold','thermalReactionStrength','condensationDensityThreshold','condensationCoolingCoefficient','thermalDiffusionRate','electricalConductionRate','combustionRate','combustionHeatScale'])if($(f))$(f).oninput=e=>{sim.rules[f]=Number(e.target.value);saveSetup(app);};for(const f of ['environmentDensity','ambientTemperature'])$(f).oninput=e=>{sim.env[f]=Number(e.target.value);updateThermometer();saveSetup(app);};$('gravityStrength').oninput=e=>{sim.env.gravityStrength=Number(e.target.value);saveSetup(app);};
  const resize=()=>{sim.resizeBox(Number($('boxWidth').value),Number($('boxHeight').value),Number($('boxDepth').value));renderer3d.updateBox();saveSetup(app);};for(const f of ['boxWidth','boxHeight','boxDepth'])$(f).oninput=resize;$('clearMoldsBtn').onclick=()=>{sim.clearMolds();saveSetup(app);toast('Molds cleared');};$('pauseBtn').onclick=()=>{sim.paused=!sim.paused;$('pauseBtn').textContent=sim.paused?'Resume':'Pause';};$('resetBtn').onclick=()=>{sim.reset();showInspection(null);toast('Simulation reset');};
  $('motionBtn').onclick=async()=>{if(gravity.isDeviceActive()){gravity.useManual();$('motionBtn').textContent='Enable Motion Controls';$('motionBtn').classList.remove('primary');toast('Motion controls disabled · manual gravity');return;}const ok=await gravity.enableDevice();if(ok){$('motionBtn').textContent='Disable Motion Controls';$('motionBtn').classList.add('primary');toast('Motion enabled · current pose calibrated');}else{gravity.useManual();$('motionBtn').textContent='Enable Motion Controls';toast('Motion unavailable · manual gravity');}};$('calibrateBtn').onclick=()=>{gravity.calibrate();toast(gravity.isDeviceActive()?'Motion calibrated':'Manual gravity centered');};$('orientationResetBtn').onclick=()=>{gravity.reset();toast('Orientation reset');};$('sensitivity').oninput=e=>{gravity.manual.sensitivity=gravity.device.sensitivity=Number(e.target.value);};
  $('quality').onchange=e=>quality.setMode(e.target.value);document.querySelectorAll('[data-debug]').forEach(b=>b.onclick=()=>{renderer3d.debugMode=b.dataset.debug;renderer2d.debugMode=b.dataset.debug;});$('graphicsPreset').onchange=e=>applyGraphicsPreset(e.target.value);for(const id of ['renderRepresentation','renderResolution','renderFraction','cloudCellSize','effectsScale'])$(id).oninput=applyManualGraphics;$('saveInspectionBtn').onclick=saveInspectedMaterial;$('closeInspectionBtn').onclick=()=>showInspection(null);$('exportBtn').onclick=()=>exportSetup(app);$('importInput').onchange=async e=>{try{const data=await importSetupFile(e.target.files[0]);applySetup(data);toast('Setup imported');}catch(err){toast(`Import failed: ${err.message}`);}};syncToolUI();
}
function bindCanvas(target){
  target.style.touchAction='none';const active=new Map();let gesture=null,single=null,pendingTouch=null,suppressSingle=false;const clearPending=()=>{if(pendingTouch){clearTimeout(pendingTouch.timer);pendingTouch=null;}};target.addEventListener('contextmenu',e=>e.preventDefault());
  const beginTwoFinger=()=>{clearPending();suppressSingle=true;const pts=[...active.values()];if(pts.length<2)return;const a=pts[0],b=pts[1];gesture={startMid:pointerMidpoint(a,b),startPinch:pointerDistance(a,b),yaw:renderer.yaw,pitch:renderer.pitch,distance:renderer.distance};single=null;nozzle.classList.remove('show');};
  const updateTwoFinger=()=>{const pts=[...active.values()];if(pts.length<2||!gesture)return;const a=pts[0],b=pts[1],mid=pointerMidpoint(a,b),pinch=pointerDistance(a,b),panScale=viewMode==='2D'?.0045:.0075,maxZoom=viewMode==='2D'?22:44;renderer.setOrbit(gesture.yaw+(mid.x-gesture.startMid.x)*panScale,gesture.pitch+(mid.y-gesture.startMid.y)*panScale,pinchCameraDistance(gesture.distance,gesture.startPinch,pinch,4,maxZoom));};
  const startSingle=e=>{const cameraOverride=e.pointerType==='mouse'&&(e.button===1||e.button===2||e.altKey);single={id:e.pointerId,x:e.clientX,y:e.clientY,yaw:renderer.yaw,pitch:renderer.pitch,distance:renderer.distance,cameraOverride};if(mode!=='camera'&&!cameraOverride)interactAt(e,false);};
  target.addEventListener('pointerdown',e=>{if(e.cancelable)e.preventDefault();ensureAudio();target.setPointerCapture(e.pointerId);active.set(e.pointerId,{x:e.clientX,y:e.clientY,pointerType:e.pointerType,button:e.button});if(active.size>=2){beginTwoFinger();return;}if(e.pointerType==='touch'&&mode!=='camera'){clearPending();pendingTouch={id:e.pointerId,timer:setTimeout(()=>{if(active.size===1&&active.has(e.pointerId)){startSingle(e);pendingTouch=null;}},70)};}else startSingle(e);});
  target.addEventListener('pointermove',e=>{if(e.cancelable)e.preventDefault();if(!active.has(e.pointerId))return;const old=active.get(e.pointerId);active.set(e.pointerId,{...old,x:e.clientX,y:e.clientY});if(active.size>=2){if(!gesture)beginTwoFinger();updateTwoFinger();return;}if(suppressSingle||pendingTouch?.id===e.pointerId)return;if(!single||single.id!==e.pointerId)return;if(mode==='camera'||single.cameraOverride){const scale=viewMode==='2D'?.005:.009;renderer.setOrbit(single.yaw+(e.clientX-single.x)*scale,single.pitch+(e.clientY-single.y)*scale,single.distance);}else interactAt(e,true);});
  const finish=e=>{if(e.cancelable)e.preventDefault();if(pendingTouch?.id===e.pointerId){clearTimeout(pendingTouch.timer);pendingTouch=null;if(active.size===1&&mode!=='camera')interactAt(e,false);}active.delete(e.pointerId);if(active.size<2)gesture=null;if(active.size===1&&!suppressSingle){const [id,p]=active.entries().next().value;single={id,x:p.x,y:p.y,yaw:renderer.yaw,pitch:renderer.pitch,distance:renderer.distance,cameraOverride:false};}else if(active.size===0){single=null;suppressSingle=false;nozzle.classList.remove('show');}};target.addEventListener('pointerup',finish);target.addEventListener('pointercancel',finish);target.addEventListener('wheel',e=>{e.preventDefault();renderer.setOrbit(renderer.yaw,renderer.pitch,renderer.distance+Math.sign(e.deltaY)*.75);},{passive:false});
}
function bindManualPad(){const pad=$('manualPad'),dot=$('manualDot');const padMove=e=>{const r=pad.getBoundingClientRect(),x=Math.max(-1,Math.min(1,(e.clientX-(r.left+r.width/2))/(r.width/2))),z=Math.max(-1,Math.min(1,(e.clientY-(r.top+r.height/2))/(r.height/2)));gravity.useManual();$('motionBtn').textContent='Enable Motion Controls';$('motionBtn').classList.remove('primary');gravity.manual.setTilt(x,z);dot.style.left=`calc(${50+x*42}% - 8px)`;dot.style.top=`calc(${50+z*36}% - 8px)`;};pad.addEventListener('pointerdown',e=>{pad.setPointerCapture(e.pointerId);padMove(e);});pad.addEventListener('pointermove',e=>{if(e.buttons)padMove(e);});}
function bindDesktopControls(){const sizes=['S','M','L','XL'];addEventListener('keydown',e=>{const tag=e.target?.tagName;if(tag==='INPUT'||tag==='SELECT'||tag==='TEXTAREA'||e.ctrlKey||e.metaKey)return;if(e.code==='Space'){e.preventDefault();sim.paused=!sim.paused;$('pauseBtn').textContent=sim.paused?'Resume':'Pause';toast(sim.paused?'Paused':'Running');return;}const key=e.key.toLowerCase(),tools={'1':'brush','2':'eraser','3':'inspect','4':'mold','5':'camera','h':'heat','c':'cool'};if(tools[key]){setMode(tools[key]);return;}if(key==='d'){setViewMode(viewMode==='2D'?'3D':'2D');return;}if(key==='r'){resetView();return;}if(key==='escape'){showInspection(null);setSheetOpen(false);return;}if(key==='['||key===']'){const current=mode==='eraser'?eraserSize:mode==='mold'?moldSize:brushSize,i=sizes.indexOf(current),next=sizes[Math.max(0,Math.min(sizes.length-1,i+(key===']'?1:-1)))];if(mode==='eraser')eraserSize=next;else if(mode==='mold')moldSize=next;else brushSize=next;syncToolUI();toast(`Tool size ${next}`);}});}
function ensureAudio(){if(!audioCtx){const AC=globalThis.AudioContext||globalThis.webkitAudioContext;if(AC)audioCtx=new AC();}if(audioCtx?.state==='suspended')audioCtx.resume().catch(()=>{});}
function reactionSound(now){if(!audioCtx||now-lastReactionSound<260||sim.reactions.eventCount===0)return;let intensity=0;for(let i=0;i<sim.reactions.eventCount;i++)intensity=Math.max(intensity,sim.reactions.eventIntensity[i]);if(intensity<.58)return;lastReactionSound=now;const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.value=120+intensity*420;gain.gain.setValueAtTime(.0001,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.025*intensity,audioCtx.currentTime+.008);gain.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.09);osc.connect(gain).connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+.1);}
function updateStats(now){if(now-lastStats<250)return;lastStats=now;const pc=sim.ps.phaseCounts(),g=sim.gravity,gr=renderer.getGraphicsSettings();$('stats').textContent=`mode ${viewMode} · particles ${sim.ps.count}/${sim.ps.capacity} · drawn ${renderer.drawCount||0}\nFPS ${fps.toFixed(0)} · sim ${simMs.toFixed(2)} ms · render ${renderMs.toFixed(2)} ms\nmaterials ${reusableMaterials().length} saved + ${sim.stats.generatedMaterials} emergent · reactions ${sim.stats.reactions} · burns ${sim.stats.combustions} · molds ${sim.molds.molds.length}\nsolid ${pc[0]} · liquid ${pc[1]} · gas ${pc[2]}\ng ${g.x.toFixed(2)} ${g.y.toFixed(2)} ${g.z.toFixed(2)}\nphysics ${quality.mode}/${sim.iterations} · load ${sim.stats.performanceTier} · display ${gr.representation} ${Math.round(gr.resolutionScale*100)}%`;$('gravityHud').textContent=viewMode==='2D'?`2D · g ${g.x.toFixed(2)} ${g.y.toFixed(2)}`:`g ${g.x.toFixed(2)} ${g.y.toFixed(2)} ${g.z.toFixed(2)}`;$('status').textContent=viewMode;updateThermometer();}
function loop(now){const frame=Math.min(.05,(now-last)/1000);last=now;fps=fps*.92+(1/Math.max(.001,frame))*.08;const gv=gravity.getGravity();sim.setGravity(gv.x,gv.y,gv.z);acc+=frame;const fixed=1/40;let steps=0,st=performance.now();while(acc>=fixed&&steps<3){sim.step(fixed);acc-=fixed;steps++;}simMs=performance.now()-st;const rt=performance.now();renderer.update(frame);renderer.render();renderMs=performance.now()-rt;reactionSound(now);const qm=quality.sample(frame*1000),targetIterations=viewMode==='2D'?Math.max(1,quality.iterations-1):quality.iterations;if(qm)toast(`Adaptive quality: ${qm}`);sim.iterations=targetIterations;updateStats(now);requestAnimationFrame(loop);}
async function boot(){renderer3d=new SceneRenderer(canvas3d,sim);renderer2d=new PlanarRenderer(canvas2d,sim);renderer=renderer3d;const restored=initMaterials();bindUI();bindCanvas(canvas3d);bindCanvas(canvas2d);bindManualPad();bindDesktopControls();addEventListener('resize',()=>{renderer3d.resize();renderer2d.resize();});if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});if(!restored)loadPreset('mixing');requestAnimationFrame(loop);}
boot().catch(err=>{console.error(err);document.body.innerHTML=`<pre style="padding:20px;color:#ff9b9b">Startup failed\n${err.stack||err}</pre>`;});
