import { graphicsPreset, normalizeGraphicsSettings } from './GraphicsSettings.mjs';

const DEG=Math.PI/180;
function mat4Perspective(fovy,aspect,near,far){const f=1/Math.tan(fovy/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);}
function mat4LookAt(ex,ey,ez,tx=0,ty=0,tz=0){let zx=ex-tx,zy=ey-ty,zz=ez-tz;let zl=Math.hypot(zx,zy,zz)||1;zx/=zl;zy/=zl;zz/=zl;let xx=zz,xz=-zx;let xl=Math.hypot(xx,xz)||1;xx/=xl;xz/=xl;const yx=zy*xz,yz=-zy*xx,yy=zz*xx-zx*xz;return new Float32Array([xx,yx,zx,0,0,yy,zy,0,xz,yz,zz,0,-(xx*ex+xz*ez),-(yx*ex+yy*ey+yz*ez),-(zx*ex+zy*ey+zz*ez),1]);}
function mat4Mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++){let v=0;for(let k=0;k<4;k++)v+=a[k*4+r]*b[c*4+k];o[c*4+r]=v;}return o;}
function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||'shader compile failed');return s;}
function program(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||'program link failed');return p;}
function makeBuffer(gl,data,usage=gl.DYNAMIC_DRAW){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,usage);return b;}
export function rayAabbIntersection(origin,dir,box){
  const mins=[-box.width/2,-box.height/2,-box.depth/2],maxs=[box.width/2,box.height/2,box.depth/2],o=[origin.x,origin.y,origin.z],d=[dir.x,dir.y,dir.z];let tmin=-Infinity,tmax=Infinity;
  for(let a=0;a<3;a++){if(Math.abs(d[a])<1e-8){if(o[a]<mins[a]||o[a]>maxs[a])return null;continue;}let t1=(mins[a]-o[a])/d[a],t2=(maxs[a]-o[a])/d[a];if(t1>t2){const q=t1;t1=t2;t2=q;}tmin=Math.max(tmin,t1);tmax=Math.min(tmax,t2);if(tmax<tmin)return null;}
  if(tmax<0)return null;const t=tmin>=0?tmin:tmax,inside=Math.min(t+.12,tmax-.01);return {x:o[0]+d[0]*inside,y:o[1]+d[1]*inside,z:o[2]+d[2]*inside,t};
}

export class SceneRenderer{
  constructor(canvas,sim){
    this.canvas=canvas;this.sim=sim;this.yaw=.65;this.pitch=.35;this.distance=12;this.debugMode='none';this.graphics=graphicsPreset('BALANCED');this.effectCap=64;this.effectCursor=0;this.effectLife=new Float32Array(this.effectCap);this.effectMaxLife=new Float32Array(this.effectCap);this.effectIntensity=new Float32Array(this.effectCap);this.cloudMap=new Map();
    const cap=sim.ps.capacity;this.positions=new Float32Array(cap*3);this.colors=new Float32Array(cap*3);this.sizes=new Float32Array(cap);this.alphas=new Float32Array(cap);this.cloudCounts=new Uint16Array(cap);this.effectPositions=new Float32Array(this.effectCap*3);this.effectColors=new Float32Array(this.effectCap*3);this.effectSizes=new Float32Array(this.effectCap);this.effectAlphas=new Float32Array(this.effectCap);
    this.gl=canvas.getContext('webgl2',{alpha:false,antialias:false,powerPreference:'high-performance'})||canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'high-performance'});this.mode2d=!this.gl;
    if(this.mode2d){this.ctx=canvas.getContext('2d');this.resize();return;}this.initPrograms();this.initBuffers();this.updateBox();this.resize();
  }
  getGraphicsSettings(){return {...this.graphics};}
  configureGraphics(settings){this.graphics=normalizeGraphicsSettings({...this.graphics,...settings});this.resize(true);}
  applyGraphicsPreset(name){this.graphics=graphicsPreset(name);this.resize(true);return this.getGraphicsSettings();}
  initPrograms(){const gl=this.gl;this.pointProgram=program(gl,`attribute vec3 aPosition;attribute vec3 aColor;attribute float aSize;attribute float aAlpha;uniform mat4 uVP;uniform float uViewportHeight;varying vec3 vColor;varying float vAlpha;void main(){vec4 clip=uVP*vec4(aPosition,1.0);gl_Position=clip;gl_PointSize=clamp(aSize*uViewportHeight/max(1.0,clip.w),2.0,72.0);vColor=aColor;vAlpha=aAlpha;}`,`precision mediump float;varying vec3 vColor;varying float vAlpha;void main(){vec2 p=gl_PointCoord-0.5;float d=length(p);if(d>0.5)discard;float soft=smoothstep(0.5,0.09,d);gl_FragColor=vec4(vColor,vAlpha*soft);}`);this.lineProgram=program(gl,`attribute vec3 aPosition;uniform mat4 uVP;void main(){gl_Position=uVP*vec4(aPosition,1.0);}`,`precision mediump float;uniform vec4 uColor;void main(){gl_FragColor=uColor;}`);this.pLoc={pos:gl.getAttribLocation(this.pointProgram,'aPosition'),color:gl.getAttribLocation(this.pointProgram,'aColor'),size:gl.getAttribLocation(this.pointProgram,'aSize'),alpha:gl.getAttribLocation(this.pointProgram,'aAlpha'),vp:gl.getUniformLocation(this.pointProgram,'uVP'),vh:gl.getUniformLocation(this.pointProgram,'uViewportHeight')};this.lLoc={pos:gl.getAttribLocation(this.lineProgram,'aPosition'),vp:gl.getUniformLocation(this.lineProgram,'uVP'),color:gl.getUniformLocation(this.lineProgram,'uColor')};}
  initBuffers(){const gl=this.gl;this.posBuffer=makeBuffer(gl,this.positions);this.colorBuffer=makeBuffer(gl,this.colors);this.sizeBuffer=makeBuffer(gl,this.sizes);this.alphaBuffer=makeBuffer(gl,this.alphas);this.effectPosBuffer=makeBuffer(gl,this.effectPositions);this.effectColorBuffer=makeBuffer(gl,this.effectColors);this.effectSizeBuffer=makeBuffer(gl,this.effectSizes);this.effectAlphaBuffer=makeBuffer(gl,this.effectAlphas);this.boxBuffer=gl.createBuffer();this.floorBuffer=gl.createBuffer();this.gridBuffer=gl.createBuffer();this.moldBuffer=gl.createBuffer();this.arrowBuffer=gl.createBuffer();}
  resize(force=false){const baseDpr=Math.min(globalThis.devicePixelRatio||1,1.5),dpr=Math.max(.5,baseDpr*this.graphics.resolutionScale),w=Math.max(1,Math.floor((this.canvas.clientWidth||innerWidth)*dpr)),h=Math.max(1,Math.floor((this.canvas.clientHeight||innerHeight)*dpr));if(force||this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}this.aspect=w/h;this.viewportHeight=h;if(!this.mode2d)this.gl.viewport(0,0,w,h);}
  setOrbit(yaw,pitch,zoom){this.yaw=yaw;this.pitch=Math.max(-1.1,Math.min(1.1,pitch));this.distance=Math.max(4,Math.min(44,zoom));}
  updateBox(){if(this.mode2d)return;const b=this.sim.env.box,hx=b.width/2,hy=b.height/2,hz=b.depth/2,c=[[-hx,-hy,-hz],[hx,-hy,-hz],[hx,hy,-hz],[-hx,hy,-hz],[-hx,-hy,hz],[hx,-hy,hz],[hx,hy,hz],[-hx,hy,hz]],e=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]],arr=[];for(const [a,d] of e)arr.push(...c[a],...c[d]);this.boxVerts=new Float32Array(arr);this.floorVerts=new Float32Array([-hx,-hy,-hz,hx,-hy,-hz,hx,-hy,hz,-hx,-hy,-hz,hx,-hy,hz,-hx,-hy,hz]);const gv=[],step=this.sim.grid.cellSize;for(let x=-hx;x<=hx+.001;x+=step)gv.push(x,-hy,0,x,hy,0);for(let y=-hy;y<=hy+.001;y+=step)gv.push(-hx,y,0,hx,y,0);this.gridVerts=new Float32Array(gv);const gl=this.gl;gl.bindBuffer(gl.ARRAY_BUFFER,this.boxBuffer);gl.bufferData(gl.ARRAY_BUFFER,this.boxVerts,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,this.floorBuffer);gl.bufferData(gl.ARRAY_BUFFER,this.floorVerts,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,this.gridBuffer);gl.bufferData(gl.ARRAY_BUFFER,this.gridVerts,gl.STATIC_DRAW);}
  cameraBasis(){const cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),eye={x:this.distance*cp*sy,y:this.distance*sp,z:this.distance*cp*cy},forward={x:-cp*sy,y:-sp,z:-cp*cy},right={x:cy,y:0,z:-sy},up={x:-sp*sy,y:cp,z:-sp*cy};return {eye,forward,right,up};}
  screenRay(clientX,clientY){const r=this.canvas.getBoundingClientRect(),nx=((clientX-r.left)/Math.max(1,r.width))*2-1,ny=1-((clientY-r.top)/Math.max(1,r.height))*2,{eye,forward,right,up}=this.cameraBasis(),tan=Math.tan(22*DEG),aspect=r.width/Math.max(1,r.height);let x=forward.x+right.x*nx*tan*aspect+up.x*ny*tan,y=forward.y+right.y*nx*tan*aspect+up.y*ny*tan,z=forward.z+right.z*nx*tan*aspect+up.z*ny*tan,l=Math.hypot(x,y,z)||1;x/=l;y/=l;z/=l;return {origin:eye,dir:{x,y,z}};}
  screenToWorld(clientX,clientY){const ray=this.screenRay(clientX,clientY);return rayAabbIntersection(ray.origin,ray.dir,this.sim.env.box);}
  computeVP(){const cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),ex=this.distance*cp*sy,ey=this.distance*sp,ez=this.distance*cp*cy;return mat4Mul(mat4Perspective(44*DEG,this.aspect,.1,100),mat4LookAt(ex,ey,ez));}
  projectWorldToScreen(x,y,z){const m=this.computeVP(),w=m[3]*x+m[7]*y+m[11]*z+m[15];if(!Number.isFinite(w)||w<=1e-6)return null;const cx=m[0]*x+m[4]*y+m[8]*z+m[12],cy=m[1]*x+m[5]*y+m[9]*z+m[13],nx=cx/w,ny=cy/w;if(!Number.isFinite(nx)||!Number.isFinite(ny)||nx<-1.25||nx>1.25||ny<-1.25||ny>1.25)return null;const r=this.canvas.getBoundingClientRect();return{x:r.left+(nx*.5+.5)*r.width,y:r.top+(1-(ny*.5+.5))*r.height,depth:w};}
  pickParticle(clientX,clientY,maxPixels=82){const ps=this.sim.ps;let best=-1,bestD2=maxPixels*maxPixels,bestDepth=Infinity;for(let i=0;i<ps.count;i++){const q=this.projectWorldToScreen(ps.x[i],ps.y[i],ps.z[i]);if(!q)continue;const dx=q.x-clientX,dy=q.y-clientY,d2=dx*dx+dy*dy;if(d2<bestD2-1e-6||(Math.abs(d2-bestD2)<1e-6&&q.depth<bestDepth)){best=i;bestD2=d2;bestDepth=q.depth;}}return best<0?null:{index:best,x:ps.x[best],y:ps.y[best],z:ps.z[best],distancePx:Math.sqrt(bestD2)};}
  updateEffects(dt){const scale=this.graphics.effectsScale;if(scale<=.001){this.effectDrawCount=0;return;}const rx=this.sim.reactions,eventStride=Math.max(1,Math.round(1/Math.max(.08,scale)));for(let e=0;e<rx.eventCount;e+=eventStride){const intensity=rx.eventIntensity[e];if(intensity<.12)continue;const i=this.effectCursor++%this.effectCap,k=i*3;this.effectPositions[k]=rx.eventX[e];this.effectPositions[k+1]=rx.eventY[e];this.effectPositions[k+2]=rx.eventZ[e];this.effectLife[i]=this.effectMaxLife[i]=(.1+.22*intensity)*scale;this.effectIntensity[i]=intensity;}let active=0;for(let i=0;i<this.effectCap;i++){this.effectLife[i]=Math.max(0,this.effectLife[i]-dt);const ratio=this.effectMaxLife[i]>0?this.effectLife[i]/this.effectMaxLife[i]:0,k=i*3,v=this.effectIntensity[i];this.effectSizes[i]=(.22+.42*v)*Math.max(.6,scale);this.effectAlphas[i]=ratio*v*.6*scale;const thermal=rx.eventThermal?.[i]||0;if(thermal>.05){this.effectColors[k]=1;this.effectColors[k+1]=.42+.3*v;this.effectColors[k+2]=.18;}else if(thermal<-.05){this.effectColors[k]=.18;this.effectColors[k+1]=.68+.2*v;this.effectColors[k+2]=1;}else{this.effectColors[k]=.35+.65*v;this.effectColors[k+1]=.72+.18*v;this.effectColors[k+2]=1;}if(ratio===0)this.effectPositions[k]=this.effectPositions[k+1]=this.effectPositions[k+2]=999;else active++;}this.effectDrawCount=active?this.effectCap:0;}
  particleVisual(ps,i,out){
    let r=ps.r[i],g=ps.g[i],b=ps.b[i],size=ps.phase[i]===2?.22:ps.phase[i]===0?.13:.16,alpha=ps.phase[i]===2?Math.min(.34,ps.opacity[i]*.45):Math.min(.9,ps.opacity[i]);
    if(this.debugMode==='temperature'){const t=Math.max(0,Math.min(1,ps.temperature[i]));r=t;g=.25;b=1-t;}else if(this.debugMode==='density'){const d=Math.max(0,Math.min(1,ps.density[i]/1.7));r=d;g=.35;b=1-d;}else if(this.debugMode==='velocity'){const v=Math.min(1,Math.hypot(ps.vx[i],ps.vy[i],ps.vz[i])/5);r=v;g=.35+.5*(1-v);b=1-v;}else if(this.debugMode==='potential'){const q=Math.max(0,Math.min(1,(ps.electricPotential[i]+1)*.5));r=q;g=.25+.35*(1-Math.abs(q-.5)*2);b=1-q;}else if(this.debugMode==='material'){const id=ps.materialId[i];r=((id*97)%255)/255;g=((id*57)%255)/255;b=((id*173)%255)/255;}else if(this.debugMode==='phase'){if(ps.phase[i]===0){r=.75;g=.78;b=.82}else if(ps.phase[i]===2){r=.65;g=.85;b=1;}}
    else if(ps.phase[i]===0){const sub=ps.solidSubdivision[i],cry=ps.crystallinity[i],grain=.72+.28*Math.abs(Math.sin((i+1)*12.9898));size=.19*(1-sub)+.065*sub+cry*.025;const brighten=.78+.28*cry;const grit=1-sub*.28*(1-grain);r=Math.min(1,r*brighten*grit+cry*.12);g=Math.min(1,g*brighten*grit+cry*.14);b=Math.min(1,b*brighten*grit+cry*.18);alpha=Math.min(1,.82+.14*(1-sub)+.04*cry);}
    out.r=r;out.g=g;out.b=b;out.size=size;out.alpha=alpha;
  }
  updateParticles(){const ps=this.sim.ps,stride=Math.max(1,Math.round(1/this.graphics.renderFraction)),v={r:0,g:0,b:0,size:0,alpha:0};let out=0;for(let i=0;i<ps.count;i+=stride){const k=out*3;this.positions[k]=ps.x[i];this.positions[k+1]=ps.y[i];this.positions[k+2]=ps.z[i];this.particleVisual(ps,i,v);this.colors[k]=v.r;this.colors[k+1]=v.g;this.colors[k+2]=v.b;this.sizes[out]=v.size;this.alphas[out]=v.alpha;out++;}this.drawCount=out;}
  updateClouds(){const ps=this.sim.ps,cell=this.graphics.cloudCellSize,stride=Math.max(1,Math.round(1/this.graphics.renderFraction)),map=this.cloudMap;map.clear();let bins=0;for(let i=0;i<ps.count;i+=stride){const qx=Math.floor((ps.x[i]+8)/cell),qy=Math.floor((ps.y[i]+8)/cell),qz=Math.floor((ps.z[i]+8)/cell),key=qx+qy*128+qz*16384;let out=map.get(key);if(out===undefined){out=bins++;map.set(key,out);const k=out*3;this.positions[k]=this.positions[k+1]=this.positions[k+2]=0;this.colors[k]=this.colors[k+1]=this.colors[k+2]=0;this.alphas[out]=0;this.cloudCounts[out]=0;}const k=out*3;this.positions[k]+=ps.x[i];this.positions[k+1]+=ps.y[i];this.positions[k+2]+=ps.z[i];this.colors[k]+=ps.r[i];this.colors[k+1]+=ps.g[i];this.colors[k+2]+=ps.b[i];this.alphas[out]+=ps.opacity[i];this.cloudCounts[out]++;}for(let out=0;out<bins;out++){const n=Math.max(1,this.cloudCounts[out]),k=out*3;this.positions[k]/=n;this.positions[k+1]/=n;this.positions[k+2]/=n;this.colors[k]/=n;this.colors[k+1]/=n;this.colors[k+2]/=n;this.sizes[out]=cell*(.48+Math.min(.42,Math.sqrt(n)*.075));this.alphas[out]=Math.min(.78,(this.alphas[out]/n)*(.2+Math.min(.65,n*.075)));}this.drawCount=bins;}
  update(dt=.016){this.updateEffects(dt);if(this.graphics.representation==='CLOUDS'&&this.debugMode==='none')this.updateClouds();else this.updateParticles();}
  uploadPointSet(pos,color,size,alpha,count,buffers){if(count<=0)return;const gl=this.gl,p=this.pLoc;gl.useProgram(this.pointProgram);gl.uniformMatrix4fv(p.vp,false,this.vp);gl.uniform1f(p.vh,this.viewportHeight);const bind=(loc,buffer,data,n)=>{gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferSubData(gl.ARRAY_BUFFER,0,data.subarray(0,count*n));gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,n,gl.FLOAT,false,0,0);};bind(p.pos,buffers[0],pos,3);bind(p.color,buffers[1],color,3);bind(p.size,buffers[2],size,1);bind(p.alpha,buffers[3],alpha,1);gl.drawArrays(gl.POINTS,0,count);}
  updateMoldBuffer(){if(this.mode2d)return 0;const arr=[];for(const m of this.sim.molds?.molds||[]){const l=m.x-m.width/2,r=m.x+m.width/2,b=m.y-m.height/2,t=m.y+m.height/2,z=m.z||0;if(m.type==='barrier'){arr.push(l,t,z,l,b,z,l,b,z,r,b,z,r,b,z,r,t,z,r,t,z,l,t,z);}else arr.push(l,t,z,l,b,z,l,b,z,r,b,z,r,b,z,r,t,z);}this.moldVerts=new Float32Array(arr);const gl=this.gl;gl.bindBuffer(gl.ARRAY_BUFFER,this.moldBuffer);gl.bufferData(gl.ARRAY_BUFFER,this.moldVerts,gl.DYNAMIC_DRAW);return this.moldVerts.length/3;}
  drawLines(buffer,count,color,mode){const gl=this.gl,l=this.lLoc;gl.useProgram(this.lineProgram);gl.uniformMatrix4fv(l.vp,false,this.vp);gl.uniform4fv(l.color,color);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.enableVertexAttribArray(l.pos);gl.vertexAttribPointer(l.pos,3,gl.FLOAT,false,0,0);gl.drawArrays(mode,0,count);}
  render(){if(this.mode2d){this.renderFallback2D();return;}const gl=this.gl;this.resize();this.vp=this.computeVP();gl.clearColor(.027,.063,.11,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);this.drawLines(this.floorBuffer,6,new Float32Array([.05,.13,.2,.5]),gl.TRIANGLES);gl.depthMask(true);this.drawLines(this.boxBuffer,this.boxVerts.length/3,new Float32Array([.35,.84,1,.62]),gl.LINES);if(this.debugMode==='grid')this.drawLines(this.gridBuffer,this.gridVerts.length/3,new Float32Array([.16,.55,.72,.28]),gl.LINES);const moldCount=this.updateMoldBuffer();if(moldCount)this.drawLines(this.moldBuffer,moldCount,new Float32Array([.82,.9,1,.88]),gl.LINES);gl.depthMask(false);this.uploadPointSet(this.positions,this.colors,this.sizes,this.alphas,this.drawCount,[this.posBuffer,this.colorBuffer,this.sizeBuffer,this.alphaBuffer]);if(this.effectDrawCount>0){gl.blendFunc(gl.SRC_ALPHA,gl.ONE);this.uploadPointSet(this.effectPositions,this.effectColors,this.effectSizes,this.effectAlphas,this.effectDrawCount,[this.effectPosBuffer,this.effectColorBuffer,this.effectSizeBuffer,this.effectAlphaBuffer]);}const g=this.sim.gravity,l=Math.hypot(g.x,g.y,g.z)||1,b=this.sim.env.box,ox=-b.width*.42,oy=b.height*.38,oz=0,scale=1.1,av=new Float32Array([ox,oy,oz,ox+g.x/l*scale,oy+g.y/l*scale,oz+g.z/l*scale]);gl.bindBuffer(gl.ARRAY_BUFFER,this.arrowBuffer);gl.bufferData(gl.ARRAY_BUFFER,av,gl.DYNAMIC_DRAW);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);this.drawLines(this.arrowBuffer,2,new Float32Array([1,.78,.24,.9]),gl.LINES);gl.depthMask(true);}
  renderFallback2D(){this.resize();const ctx=this.ctx;if(!ctx)return;const w=this.canvas.width,h=this.canvas.height,b=this.sim.env.box,scale=Math.min(w/(b.width*1.6),h/(b.height*1.55));ctx.fillStyle='#07101c';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(100,220,255,.65)';ctx.lineWidth=2;ctx.strokeRect(w/2-b.width*scale/2,h/2-b.height*scale/2,b.width*scale,b.height*scale);for(let i=0;i<this.drawCount;i++){const k=i*3,depth=this.positions[k+2],px=w/2+this.positions[k]*scale+depth*Math.sin(this.yaw)*scale*.16,py=h/2-this.positions[k+1]*scale+depth*Math.sin(this.pitch)*scale*.1,r=Math.round(this.colors[k]*255),g=Math.round(this.colors[k+1]*255),bl=Math.round(this.colors[k+2]*255);ctx.globalAlpha=this.alphas[i];ctx.fillStyle=`rgb(${r},${g},${bl})`;ctx.beginPath();ctx.arc(px,py,Math.max(2,this.sizes[i]*scale*.65),0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;ctx.strokeStyle='rgba(218,229,242,.9)';ctx.lineWidth=Math.max(1.5,scale*.04);for(const m of this.sim.molds?.molds||[]){const depth=m.z||0,px=w/2+m.x*scale+depth*Math.sin(this.yaw)*scale*.16,py=h/2-m.y*scale+depth*Math.sin(this.pitch)*scale*.1,ww=m.width*scale,hh=m.height*scale;ctx.strokeRect(px-ww/2,py-hh/2,ww,hh);}}
  dispose(){}
}
