const DEG=Math.PI/180;
function mat4Perspective(fovy,aspect,near,far){const f=1/Math.tan(fovy/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);}
function mat4LookAt(ex,ey,ez,tx=0,ty=0,tz=0){let zx=ex-tx,zy=ey-ty,zz=ez-tz;let zl=Math.hypot(zx,zy,zz)||1;zx/=zl;zy/=zl;zz/=zl;let xx=zz,xz=-zx;let xl=Math.hypot(xx,xz)||1;xx/=xl;xz/=xl;const yx=zy*xz,yz=-zy*xx,yy=zz*xx-zx*xz;return new Float32Array([xx,yx,zx,0,0,yy,zy,0,xz,yz,zz,0,-(xx*ex+xz*ez),-(yx*ex+yy*ey+yz*ez),-(zx*ex+zy*ey+zz*ez),1]);}
function mat4Mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++){let v=0;for(let k=0;k<4;k++)v+=a[k*4+r]*b[c*4+k];o[c*4+r]=v;}return o;}
function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||'shader compile failed');return s;}
function program(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||'program link failed');return p;}
function makeBuffer(gl,data,usage=gl.DYNAMIC_DRAW){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,usage);return b;}

export class SceneRenderer{
  constructor(canvas,sim){
    this.canvas=canvas;this.sim=sim;this.yaw=.65;this.pitch=.35;this.distance=12;this.debugMode='none';this.boxDirty=true;this.effectCap=96;this.effectCursor=0;this.effectLife=new Float32Array(this.effectCap);this.effectMaxLife=new Float32Array(this.effectCap);this.effectIntensity=new Float32Array(this.effectCap);
    const cap=sim.ps.capacity;this.positions=new Float32Array(cap*3);this.colors=new Float32Array(cap*3);this.sizes=new Float32Array(cap);this.alphas=new Float32Array(cap);this.effectPositions=new Float32Array(this.effectCap*3);this.effectColors=new Float32Array(this.effectCap*3);this.effectSizes=new Float32Array(this.effectCap);this.effectAlphas=new Float32Array(this.effectCap);
    this.gl=canvas.getContext('webgl2',{alpha:false,antialias:true,powerPreference:'high-performance'})||canvas.getContext('webgl',{alpha:false,antialias:true,powerPreference:'high-performance'});this.mode2d=!this.gl;
    if(this.mode2d){this.ctx=canvas.getContext('2d');this.resize();return;}
    this.initPrograms();this.initBuffers();this.updateBox();this.resize();
  }
  initPrograms(){const gl=this.gl;
    this.pointProgram=program(gl,`attribute vec3 aPosition;attribute vec3 aColor;attribute float aSize;attribute float aAlpha;uniform mat4 uVP;uniform float uViewportHeight;varying vec3 vColor;varying float vAlpha;void main(){vec4 clip=uVP*vec4(aPosition,1.0);gl_Position=clip;gl_PointSize=clamp(aSize*uViewportHeight/max(1.0,clip.w),2.0,64.0);vColor=aColor;vAlpha=aAlpha;}`,`precision mediump float;varying vec3 vColor;varying float vAlpha;void main(){vec2 p=gl_PointCoord-0.5;float d=length(p);if(d>0.5)discard;float soft=smoothstep(0.5,0.08,d);float hi=smoothstep(0.22,0.0,length(p-vec2(-0.12,0.12)));gl_FragColor=vec4(vColor+hi*0.22,vAlpha*soft);}`);
    this.lineProgram=program(gl,`attribute vec3 aPosition;uniform mat4 uVP;void main(){gl_Position=uVP*vec4(aPosition,1.0);}`,`precision mediump float;uniform vec4 uColor;void main(){gl_FragColor=uColor;}`);
    this.pLoc={pos:gl.getAttribLocation(this.pointProgram,'aPosition'),color:gl.getAttribLocation(this.pointProgram,'aColor'),size:gl.getAttribLocation(this.pointProgram,'aSize'),alpha:gl.getAttribLocation(this.pointProgram,'aAlpha'),vp:gl.getUniformLocation(this.pointProgram,'uVP'),vh:gl.getUniformLocation(this.pointProgram,'uViewportHeight')};
    this.lLoc={pos:gl.getAttribLocation(this.lineProgram,'aPosition'),vp:gl.getUniformLocation(this.lineProgram,'uVP'),color:gl.getUniformLocation(this.lineProgram,'uColor')};
  }
  initBuffers(){const gl=this.gl;this.posBuffer=makeBuffer(gl,this.positions);this.colorBuffer=makeBuffer(gl,this.colors);this.sizeBuffer=makeBuffer(gl,this.sizes);this.alphaBuffer=makeBuffer(gl,this.alphas);this.effectPosBuffer=makeBuffer(gl,this.effectPositions);this.effectColorBuffer=makeBuffer(gl,this.effectColors);this.effectSizeBuffer=makeBuffer(gl,this.effectSizes);this.effectAlphaBuffer=makeBuffer(gl,this.effectAlphas);this.boxBuffer=gl.createBuffer();this.floorBuffer=gl.createBuffer();this.gridBuffer=gl.createBuffer();this.arrowBuffer=gl.createBuffer();}
  resize(){const dpr=Math.min(globalThis.devicePixelRatio||1,1.6),w=Math.max(1,Math.floor((this.canvas.clientWidth||innerWidth)*dpr)),h=Math.max(1,Math.floor((this.canvas.clientHeight||innerHeight)*dpr));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}this.aspect=w/h;this.viewportHeight=h;if(!this.mode2d)this.gl.viewport(0,0,w,h);}
  setOrbit(yaw,pitch,zoom){this.yaw=yaw;this.pitch=Math.max(-1.1,Math.min(1.1,pitch));this.distance=Math.max(6,Math.min(22,zoom));}
  updateBox(){if(this.mode2d)return;const b=this.sim.env.box,hx=b.width/2,hy=b.height/2,hz=b.depth/2,c=[[-hx,-hy,-hz],[hx,-hy,-hz],[hx,hy,-hz],[-hx,hy,-hz],[-hx,-hy,hz],[hx,-hy,hz],[hx,hy,hz],[-hx,hy,hz]],e=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]],arr=[];for(const [a,d] of e)arr.push(...c[a],...c[d]);this.boxVerts=new Float32Array(arr);this.floorVerts=new Float32Array([-hx,-hy,-hz,hx,-hy,-hz,hx,-hy,hz,-hx,-hy,-hz,hx,-hy,hz,-hx,-hy,hz]);const gv=[],step=this.sim.grid.cellSize;for(let x=-hx;x<=hx+.001;x+=step)gv.push(x,-hy,0,x,hy,0);for(let y=-hy;y<=hy+.001;y+=step)gv.push(-hx,y,0,hx,y,0);this.gridVerts=new Float32Array(gv);const gl=this.gl;gl.bindBuffer(gl.ARRAY_BUFFER,this.boxBuffer);gl.bufferData(gl.ARRAY_BUFFER,this.boxVerts,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,this.floorBuffer);gl.bufferData(gl.ARRAY_BUFFER,this.floorVerts,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,this.gridBuffer);gl.bufferData(gl.ARRAY_BUFFER,this.gridVerts,gl.STATIC_DRAW);}
  computeVP(){const cp=Math.cos(this.pitch),sp=Math.sin(this.pitch),cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),ex=this.distance*cp*sy,ey=this.distance*sp,ez=this.distance*cp*cy;return mat4Mul(mat4Perspective(44*DEG,this.aspect,.1,100),mat4LookAt(ex,ey,ez));}
  updateEffects(dt){const rx=this.sim.reactions;for(let e=0;e<rx.eventCount;e++){const intensity=rx.eventIntensity[e];if(intensity<.12)continue;const i=this.effectCursor++%this.effectCap,k=i*3;this.effectPositions[k]=rx.eventX[e];this.effectPositions[k+1]=rx.eventY[e];this.effectPositions[k+2]=rx.eventZ[e];this.effectLife[i]=this.effectMaxLife[i]=.12+.28*intensity;this.effectIntensity[i]=intensity;}
    for(let i=0;i<this.effectCap;i++){this.effectLife[i]=Math.max(0,this.effectLife[i]-dt);const ratio=this.effectMaxLife[i]>0?this.effectLife[i]/this.effectMaxLife[i]:0,k=i*3,v=this.effectIntensity[i];this.effectSizes[i]=.24+.52*v;this.effectAlphas[i]=ratio*v*.7;this.effectColors[k]=.35+.65*v;this.effectColors[k+1]=.72+.18*v;this.effectColors[k+2]=1;if(ratio===0)this.effectPositions[k]=this.effectPositions[k+1]=this.effectPositions[k+2]=999;}
  }
  update(dt=.016){this.updateEffects(dt);const ps=this.sim.ps,n=ps.count;for(let i=0;i<n;i++){const k=i*3;this.positions[k]=ps.x[i];this.positions[k+1]=ps.y[i];this.positions[k+2]=ps.z[i];let r=ps.r[i],g=ps.g[i],b=ps.b[i];if(this.debugMode==='temperature'){const t=Math.max(0,Math.min(1,ps.temperature[i]));r=t;g=.25;b=1-t;}else if(this.debugMode==='density'){const d=Math.max(0,Math.min(1,ps.density[i]/1.7));r=d;g=.35;b=1-d;}else if(this.debugMode==='velocity'){const v=Math.min(1,Math.hypot(ps.vx[i],ps.vy[i],ps.vz[i])/5);r=v;g=.35+.5*(1-v);b=1-v;}else if(this.debugMode==='material'){const id=ps.materialId[i];r=((id*97)%255)/255;g=((id*57)%255)/255;b=((id*173)%255)/255;}else if(this.debugMode==='phase'){if(ps.phase[i]===0){r=.75;g=.78;b=.82}else if(ps.phase[i]===2){r=.65;g=.85;b=1;}}this.colors[k]=r;this.colors[k+1]=g;this.colors[k+2]=b;this.sizes[i]=ps.phase[i]===2?.22:ps.phase[i]===0?.13:.16;this.alphas[i]=ps.phase[i]===2?Math.min(.34,ps.opacity[i]*.45):Math.min(.9,ps.opacity[i]);}this.drawCount=n;}
  uploadPointSet(pos,color,size,alpha,count,buffers){const gl=this.gl,p=this.pLoc;gl.useProgram(this.pointProgram);gl.uniformMatrix4fv(p.vp,false,this.vp);gl.uniform1f(p.vh,this.viewportHeight);
    const bind=(loc,buffer,data,n)=>{gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferSubData(gl.ARRAY_BUFFER,0,data);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,n,gl.FLOAT,false,0,0);};bind(p.pos,buffers[0],pos,3);bind(p.color,buffers[1],color,3);bind(p.size,buffers[2],size,1);bind(p.alpha,buffers[3],alpha,1);gl.drawArrays(gl.POINTS,0,count);}
  drawLines(buffer,count,color,mode){const gl=this.gl,l=this.lLoc;gl.useProgram(this.lineProgram);gl.uniformMatrix4fv(l.vp,false,this.vp);gl.uniform4fv(l.color,color);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.enableVertexAttribArray(l.pos);gl.vertexAttribPointer(l.pos,3,gl.FLOAT,false,0,0);gl.drawArrays(mode,0,count);}
  render(){if(this.mode2d){this.renderFallback2D();return;}const gl=this.gl;this.resize();this.vp=this.computeVP();gl.clearColor(.027,.063,.11,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.enable(gl.BLEND);
    gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);this.drawLines(this.floorBuffer,6,new Float32Array([.05,.13,.2,.58]),gl.TRIANGLES);gl.depthMask(true);this.drawLines(this.boxBuffer,this.boxVerts.length/3,new Float32Array([.35,.84,1,.68]),gl.LINES);if(this.debugMode==='grid')this.drawLines(this.gridBuffer,this.gridVerts.length/3,new Float32Array([.16,.55,.72,.28]),gl.LINES);
    gl.depthMask(false);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);this.uploadPointSet(this.positions,this.colors,this.sizes,this.alphas,this.drawCount,[this.posBuffer,this.colorBuffer,this.sizeBuffer,this.alphaBuffer]);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);this.uploadPointSet(this.effectPositions,this.effectColors,this.effectSizes,this.effectAlphas,this.effectCap,[this.effectPosBuffer,this.effectColorBuffer,this.effectSizeBuffer,this.effectAlphaBuffer]);
    const g=this.sim.gravity,l=Math.hypot(g.x,g.y,g.z)||1,b=this.sim.env.box,ox=-b.width*.42,oy=b.height*.38,oz=0,scale=1.1;const av=new Float32Array([ox,oy,oz,ox+g.x/l*scale,oy+g.y/l*scale,oz+g.z/l*scale]);gl.bindBuffer(gl.ARRAY_BUFFER,this.arrowBuffer);gl.bufferData(gl.ARRAY_BUFFER,av,gl.DYNAMIC_DRAW);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);this.drawLines(this.arrowBuffer,2,new Float32Array([1,.78,.24,.95]),gl.LINES);gl.depthMask(true);
  }

  renderFallback2D(){this.resize();const ctx=this.ctx;if(!ctx)return;const w=this.canvas.width,h=this.canvas.height,b=this.sim.env.box,scale=Math.min(w/(b.width*1.6),h/(b.height*1.55));ctx.fillStyle='#07101c';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(100,220,255,.65)';ctx.lineWidth=2;ctx.strokeRect(w/2-b.width*scale/2,h/2-b.height*scale/2,b.width*scale,b.height*scale);for(let i=0;i<this.drawCount;i++){const k=i*3,depth=this.positions[k+2],px=w/2+this.positions[k]*scale+depth*Math.sin(this.yaw)*scale*.16,py=h/2-this.positions[k+1]*scale+depth*Math.sin(this.pitch)*scale*.1;const r=Math.round(this.colors[k]*255),g=Math.round(this.colors[k+1]*255),bl=Math.round(this.colors[k+2]*255);ctx.globalAlpha=this.alphas[i];ctx.fillStyle=`rgb(${r},${g},${bl})`;ctx.beginPath();ctx.arc(px,py,Math.max(2,this.sizes[i]*scale*.65),0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;ctx.fillStyle='rgba(255,205,80,.9)';ctx.font=`${Math.max(10,Math.round(w/40))}px monospace`;ctx.fillText('Canvas2D fallback (WebGL unavailable)',12,Math.max(20,h*.09));}
  dispose(){}
}
